<?php

namespace App\Exceptions;

use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Auth\AuthenticationException;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Throwable;
use Illuminate\Validation\ValidationException;
use Laravel\Passport\Exceptions\MissingScopeException;

class Handler extends ExceptionHandler
{
    /**
     * The list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    public function render($request, Throwable $exception)
    {
        // AsegÃºrate de manejar solo solicitudes API
        if ($request->expectsJson()) {
            return $this->handleApiException($exception);
        }

        return parent::render($request, $exception);
    }

    protected function handleApiException(Throwable $exception)
    {
        if ($exception instanceof AuthenticationException) {
            return response()->json([
                'error' => 'No autenticado. Por favor, inicie sesiÃ³n.',
            ], 401);
        }

        if ($exception instanceof AuthorizationException) {
            return response()->json([
                'error' => 'No autorizado. ' . $exception->getMessage(),
            ], 403);
        }

        if ($exception instanceof MissingScopeException) {
            return response()->json([
                'error' => 'Alcance requerido no proporcionado. ' . $exception->getMessage(),
            ], 403);
        }


        if ($exception instanceof ModelNotFoundException) {
            return response()->json([
                'error' => 'El recurso solicitado no se encontrÃ³.',
            ], 404);
        }

        if ($exception instanceof ValidationException) {
            return response()->json([
                'error' => 'Error de validaciÃ³n.',
                'messages' => $exception->errors(),
            ], 422);
        }

        if ($exception instanceof \InvalidArgumentException) {
            return response()->json([
                'error' => $exception->getMessage(),
            ], 400);
        }

        return response()->json([
            'error' => 'Error interno del servidor. ' . $exception->getMessage(),
        ], 500);

    }
}

